In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


numpy is to solve mathemetical problem like airthmetic and solve matrix


In [3]:
import numpy as np
lst=[2,4,5,6,8]
arr1=np.array(lst) # convert list into array
print(arr1)


[2 4 5 6 8]


In [4]:
arr2=list(range(1,10))


In [9]:
arr2=np.array(arr2)  #type casting
print(arr2)
a=4,
print(type(a))# by default tuple

[1 2 3 4 5 6 7 8 9]
<class 'tuple'>


In [6]:
print(type(arr2))

<class 'numpy.ndarray'>


In [11]:
la=np.array(lst)
print(type(la))
np.array(lst)
print(type(lst))

<class 'numpy.ndarray'>
<class 'list'>


In [14]:
arr2=list(range(1,20))
print(type(arr2))

arr2=np.array(arr2)
print(arr2)

<class 'list'>
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [15]:
ar3=np.arange(1,20) #no need of range fucntion and type casting to create an array
ar3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [18]:
a=np.array([1,2,3,5,5,0,5])
print(a)
print(type(a))

[1 2 3 5 5 0 5]
<class 'numpy.ndarray'>


In [24]:
ar4=np.zeros((2,20))
ar4

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [23]:
np.ones((10,5))# 10 row and 5 column

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
np.linspace(1,10,5)# 1se 10 tk number chaiye uske 5 tukde chaiye

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [28]:
print(np.arange(0,30).reshape(10,3))   # we cannot take 10,4 because when we do 10x3=30 and we have 30 elemets and if we take 10,4 then 
#we will be having 40 elemental space and have 30 elemts so it will show error

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]]


## random number

In [29]:
np.random.randint(1,5,9)

array([1, 4, 4, 4, 1, 3, 2, 3, 4], dtype=int32)

In [30]:
# creating 2 array
np.random.randint(1,5,(5,2))

array([[1, 2],
       [1, 3],
       [3, 3],
       [1, 3],
       [2, 4]], dtype=int32)

In [31]:
np.random.random(10)

array([0.54212206, 0.27095329, 0.29004212, 0.45899294, 0.29483611,
       0.8797843 , 0.05810687, 0.49922471, 0.8205568 , 0.99058457])

In [43]:
a=np.random.randint(1,60,(12,5))
print(a)
a.shape
print(a.dtype)
type(a)

[[22 31  1 56 23]
 [14 20 27  8 26]
 [59  2 48 24 15]
 [42 48  3 13 33]
 [ 2 36 34 20 47]
 [ 1  2  8 30 36]
 [52  3 44 28 20]
 [21 33 50 29 55]
 [22 16 39 29 26]
 [54  1 55 16 20]
 [26 58  3  6 36]
 [28 26 50 46  6]]
int32


numpy.ndarray

In [38]:
arr5=np.arange(60).reshape(12,5)
arr5.shape


(12, 5)

In [44]:
arr5.dtype #it tells the datatype

dtype('int64')

In [48]:
print(arr5.ndim)  # number of dimention

2


In [50]:
arr5.size #tells the size  of array

60

In [51]:
arr5.flatten()  # convert 2d array into 1d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [52]:
arr5.ravel()  ## convert 2d array into 1d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [55]:
lst_2d=[[1,2,300],[1,2,3]]
print(lst_2d)
type(lst_2d)

[[1, 2, 300], [1, 2, 3]]


list

In [57]:
np.array(lst_2d).shape

(2, 3)

#### acessing elements from array 1d to 2d array

In [63]:
arr=np.arange(60)
print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59]


In [64]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [65]:
arr[0:20:2] # with 2 gap

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

#### 2d array

In [68]:
acc=np.arange(60).reshape(12,5)
print(acc)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]]


In [69]:
acc[1,2]#43 44

np.int64(7)

In [70]:
acc[2,4]

np.int64(14)

In [81]:
acc[8:12,3:5]

array([[43, 44],
       [48, 49],
       [53, 54],
       [58, 59]])

In [84]:
acc[8:12]

array([[40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [95]:
acc[11:12,4:5]

array([[59]])

In [97]:
acc[6:7,2:3]

array([[32]])

In [98]:
acc[7:9,3:5]

array([[38, 39],
       [43, 44]])

3
(5, 15, 3)


In [102]:
acc[11][-1]

np.int64(59)

In [103]:
acc[-1,-1]

np.int64(59)

In [104]:
acc[-1][-1]

np.int64(59)

In [107]:
acc[11:,-1][0]

np.int64(59)

In [111]:
arr7=np.arange(225).reshape(5,15,3) # 5=number of table / 15=row / 3 cloumn
print(arr7)
print(arr7.ndim)
print(arr7.shape)

[[[  0   1   2]
  [  3   4   5]
  [  6   7   8]
  [  9  10  11]
  [ 12  13  14]
  [ 15  16  17]
  [ 18  19  20]
  [ 21  22  23]
  [ 24  25  26]
  [ 27  28  29]
  [ 30  31  32]
  [ 33  34  35]
  [ 36  37  38]
  [ 39  40  41]
  [ 42  43  44]]

 [[ 45  46  47]
  [ 48  49  50]
  [ 51  52  53]
  [ 54  55  56]
  [ 57  58  59]
  [ 60  61  62]
  [ 63  64  65]
  [ 66  67  68]
  [ 69  70  71]
  [ 72  73  74]
  [ 75  76  77]
  [ 78  79  80]
  [ 81  82  83]
  [ 84  85  86]
  [ 87  88  89]]

 [[ 90  91  92]
  [ 93  94  95]
  [ 96  97  98]
  [ 99 100 101]
  [102 103 104]
  [105 106 107]
  [108 109 110]
  [111 112 113]
  [114 115 116]
  [117 118 119]
  [120 121 122]
  [123 124 125]
  [126 127 128]
  [129 130 131]
  [132 133 134]]

 [[135 136 137]
  [138 139 140]
  [141 142 143]
  [144 145 146]
  [147 148 149]
  [150 151 152]
  [153 154 155]
  [156 157 158]
  [159 160 161]
  [162 163 164]
  [165 166 167]
  [168 169 170]
  [171 172 173]
  [174 175 176]
  [177 178 179]]

 [[180 181 182]
  [183 184 185]


In [128]:
arr7[4][14]=[1,2,3]
print(arr7[4][14])

[1 2 3]


In [129]:
b=np.array([2,4])
print(b)
b=b*2
print(b)
b=b+3
print(b)

[2 4]
[4 8]
[ 7 11]
